[affils]
uoft = "Department of Computer Science, University of Toronto, Canada"
[[author]]
givenName = "Zi-Jian"
familyName = "Zhang"
affil = ["uoft","Department of Physics, Southern University of Science and Technology, China"]
note = "email"
[authorNotes]
email = "zijian.academic@outlook.com"